name: Docker Image CI

on:
  push:
    tags: '*'
    branches: '*'

jobs:
  hypertest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: myrotvorets/info-from-package-json-action@1.1.0
      id: ver
      with:
        workingdir: hypertest
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: hypertest
        tags: ${{ startsWith(github.ref, 'refs/tags/hypertest@') && format('hydrofoil/hypertest:{0},hydrofoil/hypertest:latest', steps.ver.outputs.packageVersion) || 'hydrofoil/hypertest:latest' }}

  hydra-analyser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: myrotvorets/info-from-package-json-action@1.1.0
      id: ver
      with:
        workingdir: hydra-analyser
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: hydra-analyser
        tags: ${{ startsWith(github.ref, 'refs/tags/hydra-analyser@') && format('hydrofoil/hydra-analyser:{0},hydrofoil/hydra-analyser:latest', steps.ver.outputs.packageVersion) || 'hydrofoil/hydra-analyser:latest' }}
