name: Docker Image CI

on:
  push:
    tags: '*'
    branches: '*'

jobs:
  hypertest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: myrotvorets/info-from-package-json-action@1.1.0
      id: ver
      with:
        workingdir: hypertest
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: hypertest
        tags: hydrofoil/hypertest:${{ steps.ver.outputs.packageVersion }}
        push: ${{ startsWith(github.ref, 'refs/tags/hypertest@') }}

  hydra-analyser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: myrotvorets/info-from-package-json-action@1.1.0
      id: ver
      with:
        workingdir: hydra-analyser
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: hydra-analyser
        tags: hydrofoil/hydra-analyser:${{ steps.ver.outputs.packageVersion }}
        push: ${{ startsWith(github.ref, 'refs/tags/hydra-analyser@') }}
